name: 🚀 Feature Request
description: Suggest a new feature or improvement for the project
title: "[FEATURE]: Brief Description"
labels: [feature, frontend]
assignees:
  - AlvaroAlonsoAlonso
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for helping us improve this project!**

  - type: textarea
    id: feature-summary
    attributes:
      label: "Feature Summary"
      description: "Briefly describe the new feature or improvement"
      placeholder: "Example: Add a dark mode"
